# Generated by Django 3.1.3 on 2020-11-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='business_name',
            new_name='service_name',
        ),
    ]
