# Generated by Django 3.1.3 on 2020-11-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201114_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='scheduled datetime'),
        ),
    ]
