# Generated by Django 3.1.3 on 2020-11-14 13:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201114_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='qr_code_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='delivery',
            name='qr_code_text',
            field=models.CharField(default=uuid.UUID('37a94823-b821-43f0-9c73-0b19f81f5d28'), editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='stage',
            field=models.CharField(blank=True, default='ready-for-pickup', max_length=64, verbose_name='stage of delivery'),
        ),
    ]
