# Generated by Django 3.1.3 on 2020-11-14 14:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201114_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='qr_code_text',
            field=models.CharField(default=uuid.UUID('7574a6d8-0ac8-4fec-82db-c2cc7932cff9'), editable=False, max_length=40),
        ),
    ]
