# Generated by Django 3.1.3 on 2020-11-14 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201114_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='qr_code_text',
            field=models.CharField(default=uuid.UUID('01d1df18-ff76-4761-aac0-d18ef1ec91c7'), editable=False, max_length=40),
        ),
    ]
