# Generated by Django 3.1.3 on 2020-11-14 16:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201114_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=128, verbose_name='location name')),
                ('region', models.CharField(max_length=128, verbose_name='location under region')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_time',
            field=models.IntegerField(null=True, verbose_name='time to pickup (minutes)'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='satisfaction_level',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='satisfact level (out of 10)'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='api.service'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='success',
            field=models.BooleanField(blank=True, default=False, verbose_name='delivery successful'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='category of products delivered'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='qr_code_text',
            field=models.CharField(default=uuid.UUID('23478145-ebe4-4ed9-ad1f-c3439ccb462e'), editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='service',
            name='locations',
            field=models.ManyToManyField(to='api.Location'),
        ),
    ]
