# Generated by Django 3.1.3 on 2020-11-14 18:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201114_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='qr_code_text',
            field=models.CharField(default=uuid.UUID('5dbc2935-7b78-4754-a89c-04721eef2c51'), editable=False, max_length=40),
        ),
    ]
