# Generated by Django 3.1.3 on 2020-11-14 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201114_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='qr_code_text',
            field=models.CharField(default=uuid.UUID('b2660ef0-b81f-4c84-b566-b246e1e2ac3b'), editable=False, max_length=40),
        ),
    ]
