# Generated by Django 3.1.3 on 2020-11-14 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201114_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_blacklisted',
            field=models.BooleanField(blank=True, default=False, verbose_name='is in blacklist'),
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='is_blacklisted',
            field=models.BooleanField(blank=True, default=False, verbose_name='is in blacklist'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='qr_code_text',
            field=models.CharField(default=uuid.UUID('a67d4f48-db2c-4773-853f-2dc584eb725b'), editable=False, max_length=40),
        ),
    ]
