# Generated by Django 3.1.3 on 2020-11-14 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201114_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='is_blacklisted',
        ),
        migrations.AddField(
            model_name='service',
            name='is_blacklisted',
            field=models.BooleanField(blank=True, default=False, verbose_name='is in blacklist'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='qr_code_text',
            field=models.CharField(default=uuid.UUID('af76f403-05cc-4f82-b020-0f15050fee48'), editable=False, max_length=40),
        ),
    ]
